---
title: "HedibertFreitasLopes"
format: html
---

## Source

Hedibert Freitas Lopes
Graduate School of Business
University of Chicago

http://www.dme.ufrj.br/mcmc/R2WinBUGS.pdf

## Setup

```{r}
getwd()
```

```{r}
#| label: setup

pacman::p_load(tidyverse, R2WinBUGS)
```


```{r}
x = c(1.0,1.5,1.5,1.5,2.5,4.0,5.0,5.0,7.0,8.0,8.5,
      9.0,9.5,9.5,10.0,12.0,12.0,13.0,13.0,14.5,
      15.5,15.5,16.5,17.0,22.5,29.0,31.5)
y = c(1.80,1.85,1.87,1.77,2.02,2.27,2.15,2.26,2.47,
      2.19,2.26,2.40,2.39,2.41,2.50,2.32,2.32,2.43,
      2.47,2.56,2.65,2.47,2.64,2.56,2.70,2.72,2.57)
N <- length(x)
data <- list("x","y","N")

inits <- function(){
  list(alpha = 1, beta = 1, tau = 1, gamma = .9)
}

nonlinear.sim <- bugs(data = data, 
                      inits = inits, 
                      model.file = "nonlinearmodel.bug",
                      parameters = c("alpha", "beta", "tau", "gamma"),
                      n.chains = 1, n.iter = 20000, n.burnin = 5000, n.thin = 1,
                      bugs.directory = "C:/WinBUGS14",
                      codaPkg = F)
```

## Object

```{r}
# object
nonlinear.sim

# mcmc chain
dim(nonlinear.sim$sims.array)
nonlinear.sim$sims.array[1:15,1,]

par(mfrow = c(2,2))
ts.plot(nonlinear.sim$sims.array[,1,1], xlab = "iterations", ylab = "", main = "alpha")
ts.plot(nonlinear.sim$sims.array[,1,2], xlab = "iterations", ylab = "", main = "beta")
ts.plot(nonlinear.sim$sims.array[,1,3], xlab = "iterations", ylab = "", main = "tau")
ts.plot(nonlinear.sim$sims.array[,1,4], xlab = "iterations", ylab = "", main = "gamma")

```

